---
version: "3"

services:
  labkey:
    image: labkey/samplemanagement
    # build: {"context": ".", "args": ["LABKEY_VERSION=21.3-SNAPSHOT"]}
    depends_on:
      - postgres
    ports:
      - 8443:8443
    volumes:
      - ./mounts/files:/app/files
      - ./mounts/modules:/app/externalModules
      - ./mounts/logs:/app/logs
    environment:
      # - DEBUG=1

      - TOMCAT_KEYSTORE_PASSWORD=a43b3fcf46121a
      # - TOMCAT_KEYSTORE_ALIAS=tomcat
      - CERT_ALIAS=tomcat

      - POSTGRES_PASSWORD=fb4"1ee5#'f7ac323
      - POSTGRES_HOST=postgres
  postgres:
    image: postgres:13
    # silent postgres w/o needing to remake the container!
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "docker-entrypoint.sh postgres >/dev/null 2>&1"
    environment:
      - POSTGRES_PASSWORD=fb4"1ee5#'f7ac323
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
